export const allFeatures = [
  {
    category: "",
    features: [
      { name: "AI Content Generation", description: "Generate marketing copy with AI" },
      { name: "Content Templates", description: "Pre-made templates for various content types" },
      { name: "SEO Optimization", description: "AI-powered SEO recommendations" },
      { name: "Image Generation", description: "Create images with AI" },
      { name: "Content Calendar", description: "Plan and schedule content" },
    ],
  },
]

export const planFeatures = {
  free: {
    name: "Free Plan",
    description: "Perfect for individuals just getting started with AI marketing",
    included: [
      "AI Content Generation",
      "Basic Analytics Dashboard",
      "Social Media Scheduling",
      "User Seats",
      "Basic Integrations",
    ],
    limits: {
      "AI Content Generation": "Limited to 5 per day",
      "User Seats": "1 user only",
    },
  },
  starter: {
    name: "Starter Plan",
    description: "For growing businesses ready to enhance their marketing efforts",
    included: [
      "AI Content Generation",
      "Content Templates",
      "SEO Optimization",
      "Basic Analytics Dashboard",
      "Export Capabilities",
      "Social Media Scheduling",
      "Email Campaigns",
      "User Seats",
      "Basic Integrations",
    ],
    limits: {
      "AI Content Generation": "Limited to 50 per day",
      "User Seats": "Up to 3 users",
    },
  },
  pro: {
    name: "Pro Plan",
    description: "For professionals who need advanced AI marketing capabilities",
    included: [
      "AI Content Generation",
      "Content Templates",
      "SEO Optimization",
      "Image Generation",
      "Content Calendar",
      "Basic Analytics Dashboard",
      "Advanced Analytics",
      "Custom Reports",
      "Export Capabilities",
      "Social Media Scheduling",
      "Email Campaigns",
      "A/B Testing",
      "Audience Segmentation",
      "Multi-channel Campaigns",
      "User Seats",
      "Team Collaboration",
      "Priority Support",
      "Basic Integrations",
      "Advanced Integrations",
      "API Access",
      "Webhooks",
    ],
    limits: {
      "AI Content Generation": "Unlimited",
      "User Seats": "Up to 10 users",
    },
  },
  team: {
    name: "Team Plan",
    description: "For organizations that need enterprise-grade marketing solutions",
    included: [
      "AI Content Generation",
      "Content Templates",
      "SEO Optimization",
      "Image Generation",
      "Content Calendar",
      "Basic Analytics Dashboard",
      "Advanced Analytics",
      "Custom Reports",
      "Export Capabilities",
      "Real-time Monitoring",
      "Social Media Scheduling",
      "Email Campaigns",
      "A/B Testing",
      "Audience Segmentation",
      "Multi-channel Campaigns",
      "User Seats",
      "Team Collaboration",
      "Role-based Access",
      "Priority Support",
      "Dedicated Account Manager",
      "Basic Integrations",
      "Advanced Integrations",
      "API Access",
      "Webhooks",
      "Custom Integrations",
    ],
    limits: {
      "AI Content Generation": "Unlimited",
      "User Seats": "Unlimited users",
    },
  },
}